### ISSUE TITLE
Explore implementations of reliable UDP

### ISSUE THREAD

**Issue by delta4chat** [geph-official/geph5#27]
The Pipe trait of sosistab3 is now much improved, i.e., it assumes that the underlying transport layer protocol provides reliability, thus avoiding the "MuxStream over TCP" problem of sosistab2 (similar to the "TCP over TCP", it provides double reliability).

That is, in fact, sosistab3 can still use RUDP as long as the other crate implements the Pipe trait and replaces TCP with some other reliable UDP-based transport layer: the difference is that sosistab3 is already encrypted and obfuscated, so the RUDP protocol header needs to be individually encrypted and length-obfuscated, and there is no need to encrypt the RUDP payload part of RUDP.

For example, Sosistab3 over QUIC, KCP, or "Separating the Reliable Transport implementation from sosistab2" can be implemented.

Hopefully developers will not overlook the possibility that the community still needs reliable UDP protocols, not just TCP-only.

**Comment by nullchinchilla** [comment]
You're welcome to port something like sosistab2's streams over UDP to the sillad::Pipe implementation, and if the code quality is good we can integrate it into the Geph ecosystem.

But overall, I've come to believe that in *most* circumstances, reliable UDP 
- isn't as fast as TCP, especially since modern congestion control algos like BBR work much better with kernel-space high-precision timers than from userspace
- increases server load and client battery consumption substantially due to increasing kernel/userspace context switches (per-packet; this can be mitigated by batching but not completely, due to the requirement for ACKs etc)
- often works poorly with mobile NATs for a small number of long-running, mostly idle connections, which is the use case for Geph (as opposed to systems like shadowsocks that open one connection per application connection)
