### ISSUE TITLE
proxy mode ipv6 leaks

### ISSUE THREAD

**Issue by thisbefruit** [geph-official/geph5#32]
As reported by user 'mini' on the Geph forum, accessing ipv6 addresses using proxy mode bypasses Geph and leaks users' ipv6 address:

![image](https://github.com/user-attachments/assets/48c23142-5a79-474f-b5b0-832e3c9f295a)

**Comment by AnyWAT** [comment]
https://community.geph.io/t/topic/16429

**Comment by nullchinchilla** [comment]
This is now fixed. The whitelist logic goes like this:

For every SOCKS5 connection
- parse the destination into `hostname:port`
- inspect `hostname` to determine whether it belongs on the local network or not
  - if it belongs to the local network, *whitelist* it and directly connect
  - otherwise, *proxy it through Geph*.

The problem, surprisingly, is in the first step. I was splitting at the first colon, not the last, so an IPv6 destination like `2606:4700:4700::1111:443` would be incorrectly parsed as having the hostname `2606`.

This then looks like a DNS name without a TLD, which is understood as a local network host.

**Comment by AnyWAT** [comment]
新问题：WIN版VPN模式下 geph5-client.exe 罢工了。

**Comment by AnyWAT** [comment]
新动向：@mini
>刚刚又测试了下，socks代理是节点的ipv6，http代理还是我本机的ipv6，看开发者的回复貌似他只修了socks
http代理访问cloudflare dns https://[2606:4700:4700::1001]/cdn-cgi/trace 还是显示出本人的ipv6

**Comment by thisbefruit** [comment]
> 新问题：WIN版图形VPN模式下的 geph5-client.exe 罢工了。

开一个新 issue 吧，每个不同的问题开不同的 issue :smile:

**Comment by AnyWAT** [comment]
2024/11/4 16:34更新后产生的新问题，不会是硬件老旧的缘故吧？（并不是前一版本的）先前貌似正常的。
如有可能，请你测试下WIN版图形VPN模式，geph5-client.exe 运行不起来，无法连接。
拜托，我就不开 issue 了。谢谢！
