### ISSUE TITLE
Attempted & failed IPv6 connections in Linux VPN mode

### ISSUE THREAD

**Issue by thisbefruit** [geph-official/geph5#42]
VPN mode on Debian 12 seems to intercept IPv6 connections but fails to proxy them. Images on Twitter do not load as a result.

![image](https://github.com/user-attachments/assets/33d1e871-9e85-493e-9bc8-44ff083432a2)

**Comment by nullchinchilla** [comment]
This problem is triggered because connections to IPv6 addresses are captured, and "succeed" in connecting, but then break immediately if the exit server has no IPv6 support.

Since not all of our exit servers have IPv6 support, this is currently worked around in the latest commit simply by blocking all IPv6 traffic.
